name: Cargo Build, Test & Package

permissions:
  contents: write # https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_and_package:
    strategy:
      matrix:
        toolchain:
          - stable
        os:
          - ubuntu-latest
        target:
          - wasm32-wasip1
          - x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup target add ${{ matrix.target }}

      - name: Build the project
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Test the project
        if: contains(matrix.target, 'x86_64')
        run: cargo test --target ${{ matrix.target }} --release --verbose

      - name: Create the distribution packages
        run: make pack


      - name: Get the project version and name
        id: cargo_metadata
        run: |
          echo "version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_ENV
          echo "project_name=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')" >> $GITHUB_ENV

      - name: List *.tar.gz
        run: |
          ls -lah target/packages/helmster-*.tar.gz

      - name: Checksums
        run: |
          shasum -a 256 target/packages/*.tar.gz | sed s/"target\/packages\/"// > checksums.txt


      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
            target/packages/helmster-*.tar.gz
            checksums.txt

