name: Cargo Build, Test & Package

permissions:
  contents: write # https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_and_package:
    strategy:
      matrix:
        toolchain:
          - stable
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup target add ${{ matrix.target }}

      - name: Build the project
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Test the project
        if: contains(matrix.target, 'x86_64')
        run: cargo test --target ${{ matrix.target }} --release --verbose

      - name: Get the project version and name
        id: cargo_metadata
        run: |
          echo "version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_ENV
          echo "project_name=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')" >> $GITHUB_ENV

      - name: Create a package
        run: |
          BINARY_NAME=${{ env.project_name }}
          PACKAGE_NAME="${BINARY_NAME}-${{ env.version }}-${{ matrix.target }}.tar.gz"
          OUTPUT_DIR="target/${{ matrix.target }}/release"
          mkdir -p packaging
          cp ${OUTPUT_DIR}/${BINARY_NAME} packaging/
          tar -czf ${PACKAGE_NAME} -C packaging ${BINARY_NAME}

      - name: List *.tar.gz
        run: |
          ls -lah ${{ env.project_name }}-*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
            ${{ env.project_name }}-*.tar.gz
